name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create Tag
        run: |
          TAG=$(cat .version)
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git tag $TAG
          git push origin $TAG
          
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
        include:
          - os: windows
            goos: windows
            ext: .exe
          - os: linux
            goos: linux
            ext: ''
          - os: darwin
            goos: darwin
            ext: ''
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.2'

    - name: Read Version
      id: read_version
      run: |
        echo "VERSION=$(cat .version)" >> $GITHUB_ENV
        echo "REVISION=$(git rev-parse HEAD)" >> $GITHUB_ENV

    - name: Print Version
      run: echo "Version is $VERSION"

    - name: Build
      run: |
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.arch }} go build -ldflags "-X github.com/danecwalker/docmd/internal/meta.Version=${{env.VERSION}} -X github.com/danecwalker/docmd/internal/meta.Revision=${{env.REVISION}}" -o bin/docmd-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }} ./cmd/docmd

    - name: Upload Binary
      uses: actions/upload-artifact@v2
      with:
        name: docmd-${{ matrix.os }}-${{ matrix.arch }}
        path: bin/docmd-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}